// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20241025215255_FirstMigrations")]
    partial class FirstMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CarBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("CarBrand", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = new Guid("848e5f39-22c7-47d4-b1a7-ea53fe06cbae"),
                            Description = "Es un fabricante de automóviles y camiones con sede en Detroit, Míchigan, Estados Unidos, como una división de General Motors.",
                            Name = "Chevrolet",
                            State = true
                        },
                        new
                        {
                            Id = 2,
                            BrandId = new Guid("655a0bec-4a5e-49cf-a10f-660b92219438"),
                            Description = "Es una firma de origen japonés fundada en 1920 y con sede en la ciudad de Hiroshima.",
                            Name = "Mazda",
                            State = true
                        },
                        new
                        {
                            Id = 3,
                            BrandId = new Guid("12b8c32f-afe4-44c8-9f21-ccf19febb7a9"),
                            Description = "Es una empresa multinacional fabricante de automóviles de origen estadounidense.",
                            Name = "Ford",
                            State = true
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("User", (string)null);

                    b.ToView("UserView", (string)null);

                    b.ToSqlQuery("INSERT INTO User (Username, Password) \r\n                                                    VALUES ('admin', 'admin'), ('developer', 'developer')");
                });
#pragma warning restore 612, 618
        }
    }
}
